"""
Format RCA results into markdown (for PR comments) and JSON (for artifacts).
"""

import json
from typing import Any


def rca_to_markdown(rca: dict[str, Any], metadata: dict[str, str]) -> str:
    """Format an RCA result dict into a GitHub-flavored markdown comment."""

    category_emoji = {
        "test_failure": "🧪",
        "compilation_error": "🔨",
        "dependency_issue": "📦",
        "timeout": "⏰",
        "resource_exhaustion": "💾",
        "infra_flake": "🔄",
        "config_error": "⚙️",
        "unknown": "❓",
    }

    confidence_badge = {
        "high": "🟢 High",
        "medium": "🟡 Medium",
        "low": "🔴 Low",
    }

    category = rca.get("category", "unknown")
    emoji = category_emoji.get(category, "❓")
    conf = rca.get("confidence", "low")
    conf_badge = confidence_badge.get(conf, conf)

    bta = rca.get("build_time_analysis", {})
    duration = bta.get("total_duration_minutes")
    exceeded = bta.get("exceeded_threshold", False)
    slowest = bta.get("slowest_step", "N/A")
    slowest_dur = bta.get("slowest_step_duration_minutes")

    time_section = ""
    if duration is not None:
        time_icon = "🚨" if exceeded else "✅"
        time_section = f"""
### {time_icon} Build Time Analysis
| Metric | Value |
|--------|-------|
| Total duration | {duration:.1f} min |
| Threshold exceeded | {"**YES**" if exceeded else "No"} |
| Slowest step | {slowest} |
| Slowest step duration | {f"{slowest_dur:.1f} min" if slowest_dur else "N/A"} |
"""

    components = rca.get("failed_components", [])
    components_section = ""
    if components:
        comp_list = "\n".join(f"- `{c}`" for c in components[:10])
        components_section = f"\n### Failed Components\n{comp_list}\n"

    errors = rca.get("error_messages", [])
    errors_section = ""
    if errors:
        err_list = "\n".join(f"```\n{e[:300]}\n```" for e in errors[:5])
        errors_section = f"\n### Key Error Messages\n{err_list}\n"

    md = f"""## {emoji} Build Failure RCA — `{metadata.get("workflow_name", "")}`

> **Confidence**: {conf_badge} | **Category**: `{category}` | **Branch**: `{metadata.get("branch", "")}` | **Commit**: `{metadata.get("sha", "")[:8]}`

### Root Cause
{rca.get("root_cause", "Unable to determine")}
{time_section}{components_section}{errors_section}
### Recommendation
{rca.get("recommendation", "Review build logs manually")}

{f"> **Note**: {rca['additional_notes']}" if rca.get("additional_notes") else ""}

---
<sub>🤖 Generated by Build RCA Agent (Gemma 3 27B) | [View full logs]({metadata.get("run_url", "#")})</sub>
"""
    return md.strip()


def rca_to_json(
    rca: dict[str, Any], metadata: dict[str, str]
) -> str:
    """Create the full RCA report as a JSON string."""
    report = {
        "rca": rca,
        "metadata": metadata,
        "version": "1.0",
    }
    return json.dumps(report, indent=2, default=str)


def rca_to_slack_payload(
    rca: dict[str, Any], metadata: dict[str, str]
) -> dict[str, Any]:
    """Build a Slack incoming webhook payload for the RCA result."""
    category = rca.get("category", "unknown")
    root_cause = rca.get("root_cause", "Unable to determine")
    recommendation = rca.get("recommendation", "Review manually")
    run_url = metadata.get("run_url", "#")
    workflow = metadata.get("workflow_name", "unknown")
    branch = metadata.get("branch", "unknown")

    return {
        "text": f"Build Failure RCA: {workflow} on {branch}",
        "blocks": [
            {
                "type": "header",
                "text": {
                    "type": "plain_text",
                    "text": f"{workflow} — Build Failed",
                },
            },
            {
                "type": "section",
                "fields": [
                    {"type": "mrkdwn", "text": f"*Branch:*\n`{branch}`"},
                    {"type": "mrkdwn", "text": f"*Category:*\n`{category}`"},
                    {"type": "mrkdwn", "text": f"*Confidence:*\n{rca.get('confidence', 'low')}"},
                    {"type": "mrkdwn", "text": f"*Actor:*\n{metadata.get('actor', 'unknown')}"},
                ],
            },
            {
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": f"*Root Cause:*\n{root_cause}",
                },
            },
            {
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": f"*Recommendation:*\n{recommendation}",
                },
            },
            {
                "type": "actions",
                "elements": [
                    {
                        "type": "button",
                        "text": {"type": "plain_text", "text": "View Build Logs"},
                        "url": run_url,
                    }
                ],
            },
        ],
    }
